"""
End-to-end evaluation harness for the Campus Dining Unofficial Guide.

Spec source: planning.md — Evaluation Plan section (5 questions).

Runs the full retrieval + generation pipeline (query.ask) against every
eval-plan question and writes a persistent, reviewable Markdown report to
eval_report.md. This makes evaluation a first-class artifact: a reader can
open eval_report.md and see retrieval distances, sources, and generated
answers without re-running anything.

Usage:
    python evaluate.py                # run full eval, write eval_report.md
    python evaluate.py --out FILE.md  # write report to a custom path
"""

import argparse
from datetime import datetime, timezone

from query import ask

# ---------------------------------------------------------------------------
# Eval-plan questions (planning.md) with expected answers and a keyword an
# automated check can look for in the generated answer. Keywords are a proxy,
# not a full accuracy judgment — but they turn "eyeball the terminal" into a
# reproducible pass/fail signal that ships with the report.
# ---------------------------------------------------------------------------

EVAL_QUESTIONS = [
    {
        "id": 1,
        "question": "What dining hall does the Cornell Daily Sun name as Cornell's best?",
        "expected": "The article specifically names Abou-Alfa as Cornell's best dining hall.",
        "expected_keywords": ["abou-alfa", "abou alfa"],
    },
    {
        "id": 2,
        "question": "What do University of Miami students say about vegan options on campus?",
        "expected": (
            "The Miami Hurricane reports that vegan-friendly options at UM have been "
            "increasing, with students noting improvements at Hecht-Stanford dining."
        ),
        "expected_keywords": ["vegan", "tofu", "unappetizing"],
    },
    {
        "id": 3,
        "question": "What late-night food options does BU Today describe for hungry students after hours?",
        "expected": (
            "BU Today lists specific on-campus locations (e.g., the George Sherman Union "
            "late-night options) available after normal dining hall hours."
        ),
        "expected_keywords": ["george sherman", "late-night", "late night"],
    },
    {
        "id": 4,
        "question": "How do Harvard students describe the food quality changes after HUDS updated its menu?",
        "expected": (
            "The Crimson article captures student complaints about specific menu changes "
            "that students considered a downgrade."
        ),
        "expected_keywords": ["junk food", "huds"],
    },
    {
        "id": 5,
        "question": "What does the Columbia Spectator recommend for students who want a late-night snack on campus?",
        "expected": (
            "The Spectator's ultimate guide mentions JJ's Place as Columbia's late-night "
            "dining option, open when other dining halls are closed."
        ),
        "expected_keywords": ["jj's place", "jj's"],
    },
]

NO_INFO_PHRASE = "i don't have enough information on that in my sources"


def _domain(url: str) -> str:
    return url.split("//")[-1].split("/")[0]


def _judge(answer: str, expected_keywords: list) -> str:
    """Automated proxy for accuracy: does the answer contain an expected keyword?"""
    lowered = answer.lower()
    if NO_INFO_PHRASE in lowered:
        return "GROUNDED REFUSAL (no matching keyword found — check if source was ingested)"
    if any(kw in lowered for kw in expected_keywords):
        return "PASS (expected keyword found)"
    return "FLAG FOR REVIEW (no expected keyword found — verify manually)"


def run_evaluation():
    rows = []
    for item in EVAL_QUESTIONS:
        result = ask(item["question"])
        verdict = _judge(result["answer"], item["expected_keywords"])
        rows.append({**item, "result": result, "verdict": verdict})
    return rows


def render_report(rows) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Evaluation Report",
        "",
        f"Generated by `python evaluate.py` on {generated_at}.",
        "This file is a persisted artifact of a full retrieval + generation run "
        "against every question in planning.md's Evaluation Plan — it does not "
        "need to be re-run to be reviewed.",
        "",
        "## Summary",
        "",
        "| # | Question | Verdict |",
        "|---|----------|---------|",
    ]
    for row in rows:
        q = row["question"]
        lines.append(f"| {row['id']} | {q} | {row['verdict']} |")

    lines += ["", "---", ""]

    for row in rows:
        result = row["result"]
        lines.append(f"## Q{row['id']}: {row['question']}")
        lines.append("")
        lines.append(f"**Expected:** {row['expected']}")
        lines.append("")
        lines.append(f"**Verdict:** {row['verdict']}")
        lines.append("")
        lines.append("**Retrieved chunks:**")
        lines.append("")
        lines.append("| # | Distance | Source | Preview |")
        lines.append("|---|----------|--------|---------|")
        for i, chunk in enumerate(result["chunks"], 1):
            preview = chunk["text"][:100].replace("|", "/").replace("\n", " ")
            lines.append(
                f"| {i} | {chunk['distance']:.4f} | {_domain(chunk['source_url'])} | {preview}... |"
            )
        lines.append("")
        lines.append("**Generated answer:**")
        lines.append("")
        lines.append(f"> {result['answer']}")
        lines.append("")
        lines.append("**Sources cited:**")
        for s in result["sources"]:
            lines.append(f"- {s}")
        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="eval_report.md",
                        help="Path to write the Markdown report (default: eval_report.md)")
    args = parser.parse_args()

    print(f"Running {len(EVAL_QUESTIONS)} eval-plan questions through the full pipeline...")
    rows = run_evaluation()
    report = render_report(rows)

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"\nWrote report to {args.out}")
    for row in rows:
        print(f"  Q{row['id']}: {row['verdict']}")
